### PR TITLE
Align path to the rest of the tests paths

### PR DESCRIPTION
**Pull request by sarroutbi**

### CODE REVIEW

**Comment by sopos** [comment]
The `PURPOSE` and `Makefile` files are not necessary, nowadays. The only usage is `Makefile` for 1MT, otherwise we need just `.fmf` files for `tmt`.

I mean, it is not really important to fix the content there, except for the `Requires` and `RhtsRequires` to keep 1MT working.

**Review by sopos — APPROVED** [review]

**Comment by sarroutbi** [comment]
Thanks for the review, @sopos . Please, do not merge. I still need to try it against an OpenShift cluster

**Comment by sopos** [comment]
Sure, it is the preferred way to let you to merge it. https://github.com/RedHat-SP-Security/tests#pr-merge

**Comment by sarroutbi** [comment]
```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   /CoreOS/tang-operator/Sanity
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: [ 11:42:59 ] :: [   LOG    ] :: Phases fingerprint:  Mf0VrTCW
:: [ 11:42:59 ] :: [   LOG    ] :: Asserts fingerprint: z7uggvTj
:: [ 11:42:59 ] :: [   LOG    ] :: JOURNAL XML: /var/tmp/beakerlib-Klpze5q/journal.xml
:: [ 11:42:59 ] :: [   LOG    ] :: JOURNAL TXT: /var/tmp/beakerlib-Klpze5q/journal.txt
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   Duration: 1348s
::   Phases: 17 good, 0 bad
::   OVERALL RESULT: PASS (/CoreOS/tang-operator/Sanity)

```

**Pull request merged**
