### PR TITLE
usbguard/Sanity/dbus: Initial commit

### PR DESCRIPTION
**Pull request by Cropi**
Cover the following dbus actions:

- setParameter, getParameter
- listRules, appendRule, removeRule
- listDevices, applyDevicePolicy

### CODE REVIEW

**Comment by sopos** [comment]
Looks good for the first sight. What I miss there is a check for a regular user to be allow to preform certain actions.

**Comment by Cropi** [comment]
Thanks, then I will extend the test suite with that.

**Comment by Cropi** [comment]
Each phase of the test case consists of three parts, including:

1. Execute supported actions as root.
2. Execute supported actions as a non-root user with no privilege.
3. Execute supported actions as a non-root user with privilege to certain actions.

**Comment by sopos** [comment]
I added some requirements definitions and I refactored the test a bit. Please squash before merge.

**Pull request merged**
