### PR TITLE
Correct rsyslog/Sanity/config.enabled

### PR DESCRIPTION
**Pull request by Cropi**

### CODE REVIEW

**Comment by sopos** [comment]
the error is stil present even if noconfig.enbaled is used for the parser
```
rsyslogd: parser module name 'rsyslog.pmrfc3164' is unknown [v8.2102.0-2.fc35 try https://www.rsyslog.com/e/2209 ]
rsyslogd: error: parser 'parser.rfc3164' unknown at this time (maybe defined too late in rsyslog.conf?) [v8.2102.0-2.fc35 try https://www.rsyslog.com/e/2159 ]
```
see http://artifacts.dev.testing-farm.io/9e56b183-ee33-4780-ac1f-b8886dee335a/
You just changed the check to look for different pattern.
So there's still some issue with the parser itself.

**Comment by Cropi** [comment]
I forgot to remove the prefix. I am asking for retest :) thanks

**Comment by sopos** [comment]
you can easily see the result in the packit runs

**Pull request merged**
