### PR TITLE
tang/Sanity/simple-tang-server-start: add test for the key generator

### PR DESCRIPTION
**Pull request by sergio-correia**

### CODE REVIEW

**Review by ZelenyMartin — APPROVED** [review]
New test correctly fails on tang-7-7.el8

**Comment by Koncpa** [comment]
LGTM, we can merge it.. WDYT @ZelenyMartin ?

**Review by Koncpa — APPROVED** [review]

**Comment by ZelenyMartin** [comment]
I suggest the author of PR should merge it (after approval). What do you think, @sergio-correia?

**Comment by sergio-correia** [comment]
Merged, thanks for the review.

**Pull request merged**
