### PR TITLE
Tang operator based on beakerlib + Key management

### PR DESCRIPTION
**Pull request by sarroutbi**
Base test for tang-operator. It includes different tests regarding:

Configuration
Deployment
Functional (key retrieving, key rotation)
Scale
Legacy tests
Key management tests (key retrieve, rotation and deletion via TangServer status/spec)

Test allows execution on minikube and also against a real cluster. It also allows configuring client to use (oc, kubectl, etc.)

### CODE REVIEW

**Comment by sarroutbi** [comment]
@sergio-correia , @ZelenyMartin , @sopos : Pull Request ready, please review when possible

**Comment by sarroutbi** [comment]
@TomasTomecek : did something change recently on packit infra or related? Checks are dumping next error:

"Artemis API call failed: Condition 'api_call' failed to pass within given time"

This issue sounds pretty recent to me, not related to the changes I have pushed ...

**Comment by thrix** [comment]
> @TomasTomecek : did something change recently on packit infra or related? Checks are dumping next error:
> 
> "Artemis API call failed: Condition 'api_call' failed to pass within given time"
> 
> This issue sounds pretty recent to me, not related to the changes I have pushed ...

@sarroutbi sorry no, it was an outage, things should be better now, sorry for the inconvenience

**Comment by sarroutbi** [comment]
> > @TomasTomecek : did something change recently on packit infra or related? Checks are dumping next error:
> > "Artemis API call failed: Condition 'api_call' failed to pass within given time"
> > This issue sounds pretty recent to me, not related to the changes I have pushed ...
> 
> @sarroutbi sorry no, it was an outage, things should be better now, sorry for the inconvenience

Ok, thanks for clarifying @thrix

**Pull request merged**
