### PR TITLE
Tang operator testing based on beakerlib

### PR DESCRIPTION
**Pull request by sarroutbi**
Base test for tang-operator. It includes different tests regarding:

- Configuration
- Deployment
- Functional (key retrieving, key rotation)
- Scale
- Legacy tests

Test allows execution based on CRC, minikube and also against a real cluster. It also allows configuring client to use (oc, kubectl, etc.)

### CODE REVIEW

**Comment by TomasTomecek** [comment]
sorry about the breakage of the build: we already have a fix: https://github.com/rebase-helper/rebase-helper/pull/872

**Comment by sarroutbi** [comment]
> sorry about the breakage of the build: we already have a fix: [rebase-helper/rebase-helper#872](https://github.com/rebase-helper/rebase-helper/pull/872)

What is the correct procedure to regenerate build? I push forced a change to launch checks again, but they are still failing ...

**Comment by TomasTomecek** [comment]
You can reschedule a build by typing
```
/packit build
```

Sadly, there is an issue that we cannot parse the spec file, hence the exception.

You should be able to workaround by adding this on line 5 in tests.spec file
```
Source0: README.md
```

The issue is that the spec file parsing library is unable to parse the spec because it does not define any sources (which is very uncommon usually)

Once the referenced PR is merged and released, it should be fixed on our side, which can take even a week.

**Comment by sarroutbi** [comment]
> You can reschedule a build by typing
> 
> ```
> /packit build
> ```
> 
> Sadly, there is an issue that we cannot parse the spec file, hence the exception.
> 
> You should be able to workaround by adding this on line 5 in tests.spec file
> 
> ```
> Source0: README.md
> ```
> 
> The issue is that the spec file parsing library is unable to parse the spec because it does not define any sources (which is very uncommon usually)
> 
> Once the referenced PR is merged and released, it should be fixed on our side, which can take even a week.

Ok, thanks for clarifying.

@ZelenyMartin : take this into account for PR review, please

**Comment by TomasTomecek** [comment]
I was a bit lost in the beakerlib output so I asked @thrix to check it out: he says that you need to install oc, minikube and operator-sdk if you want those tests to execute in TF

**Comment by sarroutbi** [comment]
> I was a bit lost in the beakerlib output so I asked @thrix to check it out: he says that you need to install oc, minikube and operator-sdk if you want those tests to execute in TF

I have been including modifications to bypass EPEL7 and Fedora compilations. Both are returning 0, it can be checked in the execution (http://artifacts.dev.testing-farm.io/5385096c-c861-4a20-b6a7-7fd412fcf595):
...
CI EXECUTION RESULT:[0]

However, Tests continue failing ...

**Comment by TomasTomecek** [comment]
wow, you actually made this work :O I'm impressed

**Comment by sarroutbi** [comment]
@sergio-correia , @ZelenyMartin , @sopos : this PR is ready from my side. No more commits will be added apart from the review suggestions.

**Comment by sarroutbi** [comment]
New PR created to handle this + key management: #63

**Pull request closed without merging**
